plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = "1.7.0"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
    maven {
        url = "https://maven.notenoughupdates.org/releases"

        content {
            includeGroup "org.notenoughupdates.moulconfig"
        }
    }

    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation("org.notenoughupdates.moulconfig:${project.moulconfig_flavour}:${project.moulconfig_version}")
    include "org.notenoughupdates.moulconfig:${project.moulconfig_flavour}:${project.moulconfig_version}"
    modImplementation("net.fabricmc:fabric-language-kotlin:${project.flk_version}")
    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
	
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
        expand "version": project.version,
            "minecraft_version": project.minecraft_version,
            "loader_version": project.loader_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

tasks.named("remapJar") {
    archiveVersion.set("")
    project.base.archivesName.set("asuaddons-${project.minecraft_version}-9999999")
}